name: Check steam censorship

on:
  # schedule:
  #   - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape steamcommunity websites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9.9
          cache: pipenv
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install
      - name: Scrape
        run: pipenv run python scrape.py
        shell: bash
